#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
#brew tap homebrew/dupes
brew install vim

# Install everything else
brew install ack
brew install asciinema
brew install autojump
brew install clisp
brew install clojure
brew install ctags
brew install dockermachine
brew install emacs-mac
brew install fontconfig
brew install gh
brew install git
brew install neofetch
brew install node
brew install oauth2l
brew install openjdk
brew install openjpeg
brew install pandoc
brew install pipenv
brew install pixman
brew install pre-commit
brew install protobuf
brew install python
brew install rocksdb
brew install rtmpdump
brew install rubberband
brew install ruby
brew install screenresolution
brew install snappy
brew install go
brew install grc
brew install htop
brew install hugo
brew install imagemagick
brew install jmxterm
brew install jpeg
brew install jq
brew install kafkacat
brew install kotlin
brew install kt
brew install kubectx
brew install kubernetes-cli
brew install kubetail
brew install kustomize
brew install lame
brew install lazygit
brew install lolcat
brew install macvim
brew install maven
#brew install postgresql
brew install reattach-to-user-namespace
brew install rlwrap
brew install scala
brew install sphinx-doc
brew install spotify-tui
brew install sqlite
brew install tig
brew install tmate
brew install tmux
brew install todo-txt
brew install tree
brew install vim
brew install vimpager
brew install watch
brew install wget
brew install xmlstarlet
brew install yabai
brew install youtube-dl
brew install yq
brew install zsh
brew install zsh-kubectl-prompt
brew install zsh-syntax-highlight

#brew install giter8
#brew install gnupg
#brew install haskell-platform

# Remove outdated versions from the cellar
brew cleanup
