#!/bin/sh
#
# PIP
#
# This installs some of the common dependencies needed (or at least desired)
# using pip.

# Check for pip
if test ! $(which pip3)
then
  echo "  x You should probably install pip first:"
  echo "    brew install python"
  exit
else
  echo "  + pip found."
fi

pip3 install -U pip

pip3 install cachetools
pip3 install google-api-core
pip3 install google-auth
pip3 install google-cloud-bigquery
pip3 install google-cloud-core
pip3 install google-resumable-media
pip3 install googleapis-common-protos
pip3 install powerline-status
pip3 install setuptools
pip3 install virtualenv
pip3 install websocket-client
pip3 install wheel

